Repository AY2425S2-CS2103T-F10-1/tp, pull requests merged in 2025-04, with the labels that each got.

#134 Fix meeting view not updating
  src/main/java/syncsquad/teamsync/components/timetable/TimetableChart.java
  src/main/java/syncsquad/teamsync/controller/TimetableController.java
Labels: type.bug, priority.high, alpha-bug

#130 Add tests for AddMeetingCommand and AddModuleCommand
  .gitignore
  src/main/java/syncsquad/teamsync/logic/commands/EditCommand.java
  src/main/java/syncsquad/teamsync/logic/parser/EditCommandParser.java
  src/main/java/syncsquad/teamsync/logic/parser/ParserUtil.java
  src/test/java/syncsquad/teamsync/logic/commands/AddMeetingCommandTest.java
  src/test/java/syncsquad/teamsync/logic/commands/AddModuleCommandTest.java
  src/test/java/syncsquad/teamsync/logic/commands/CommandTestUtil.java
  src/test/java/syncsquad/teamsync/logic/commands/DeleteModuleCommandTest.java
  src/test/java/syncsquad/teamsync/logic/commands/EditCommandTest.java
  src/test/java/syncsquad/teamsync/logic/parser/AddMeetingCommandParserTest.java
  src/test/java/syncsquad/teamsync/logic/parser/AddModuleCommandParserTest.java
  src/test/java/syncsquad/teamsync/logic/parser/AddressBookParserTest.java
  src/test/java/syncsquad/teamsync/logic/parser/DeleteModuleCommandParserTest.java
  src/test/java/syncsquad/teamsync/logic/parser/ParserUtilTest.java
  src/test/java/syncsquad/teamsync/model/meeting/MeetingTest.java
  src/test/java/syncsquad/teamsync/model/meeting/UniqueMeetingListTest.java
  src/test/java/syncsquad/teamsync/model/module/DayTest.java
  src/test/java/syncsquad/teamsync/model/module/ModuleTest.java
  src/test/java/syncsquad/teamsync/model/person/PersonTest.java
  src/test/java/syncsquad/teamsync/model/person/UniquePersonListTest.java
  src/test/java/syncsquad/teamsync/model/tag/TagTest.java
  src/test/java/syncsquad/teamsync/testutil/ModuleBuilder.java
  src/test/java/syncsquad/teamsync/testutil/TypicalAddressBook.java
Labels: type.task, priority.high, severity.high

#139 As a user I can change the week displayed in the timetable #138
  src/main/java/syncsquad/teamsync/controller/MainWindowController.java
  src/main/java/syncsquad/teamsync/controller/TimetableController.java
  src/main/java/syncsquad/teamsync/logic/Logic.java
  src/main/java/syncsquad/teamsync/logic/LogicManager.java
  src/main/java/syncsquad/teamsync/logic/commands/ShowDateCommand.java
  src/main/java/syncsquad/teamsync/logic/commands/exceptions/CommandException.java
  src/main/java/syncsquad/teamsync/logic/parser/AddressBookParser.java
  src/main/java/syncsquad/teamsync/logic/parser/ShowDateCommandParser.java
  src/main/java/syncsquad/teamsync/model/Model.java
  src/main/java/syncsquad/teamsync/model/ModelManager.java
  src/main/java/syncsquad/teamsync/model/TimetableWeek.java
  src/main/java/syncsquad/teamsync/viewmodel/CurrentWeekViewModel.java
  src/main/java/syncsquad/teamsync/viewmodel/MainViewModel.java
  src/test/java/syncsquad/teamsync/logic/commands/AddMeetingCommandTest.java
  src/test/java/syncsquad/teamsync/logic/commands/AddModuleCommandTest.java
  src/test/java/syncsquad/teamsync/logic/commands/AddPersonCommandTest.java
  src/test/java/syncsquad/teamsync/logic/commands/DeleteModuleCommandTest.java
  src/test/java/syncsquad/teamsync/logic/commands/ListMeetingsCommandTest.java
  src/test/java/syncsquad/teamsync/logic/parser/AddMeetingCommandParserTest.java
  src/test/java/syncsquad/teamsync/viewmodel/MainViewModelTest.java
Labels: type.story, priority.high

#166 Update UG
  docs/UserGuide.md
Labels: type.task, priority.high, severity.high

#167 Update design section of developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/ViewModelClassDiagram.png
  docs/images/johndoe.png
  src/main/java/syncsquad/teamsync/controller/MainWindowController.java
  src/main/java/syncsquad/teamsync/controller/UiManager.java
  src/main/java/syncsquad/teamsync/logic/commands/meeting/AddMeetingCommand.java
  src/main/java/syncsquad/teamsync/logic/commands/meeting/DeleteMeetingCommand.java
  src/main/java/syncsquad/teamsync/logic/commands/module/AddModuleCommand.java
  src/main/java/syncsquad/teamsync/logic/commands/module/DeleteModuleCommand.java
  src/main/java/syncsquad/teamsync/logic/commands/person/AddPersonCommand.java
  src/main/java/syncsquad/teamsync/logic/commands/person/DeletePersonCommand.java
  src/main/java/syncsquad/teamsync/logic/commands/person/EditCommand.java
  src/main/java/syncsquad/teamsync/logic/commands/person/FindCommand.java
  src/main/java/syncsquad/teamsync/viewmodel/MainViewModel.java
Labels: type.task, priority.high

#180 Fix various alpha bugs
  src/main/java/syncsquad/teamsync/logic/commands/module/AddModuleCommand.java
  src/main/java/syncsquad/teamsync/logic/commands/person/AddPersonCommand.java
  src/main/java/syncsquad/teamsync/model/person/Name.java
  src/main/java/syncsquad/teamsync/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/syncsquad/teamsync/logic/commands/AddModuleCommandTest.java
  src/test/java/syncsquad/teamsync/model/person/PersonTest.java
Labels: priority.high, severity.high, alpha-bug

#182 Add implementation to DG
  docs/DeveloperGuide.md
  docs/diagrams/MeetingAddActivityDiagram.puml
  docs/diagrams/MeetingDeleteActivityDiagram.puml
  docs/diagrams/ModuleAddActivityDiagram.puml
  docs/diagrams/ModuleDeleteActivityDiagram.puml
  docs/diagrams/PersonAddActivityDiagram.puml
  docs/diagrams/PersonDeleteActivityDiagram.puml
  docs/diagrams/PersonEditActivityDiagram.puml
  docs/diagrams/PersonFindActivityDiagram.puml
  docs/diagrams/PersonListActivityDiagram.puml
  docs/images/MeetingAddActivityDiagram.png
  docs/images/MeetingDeleteActivityDiagram.png
  docs/images/ModuleAddActivityDiagram.png
  docs/images/ModuleDeleteActivityDiagram.png
  docs/images/PersonAddActivityDiagram.png
  docs/images/PersonDeleteActivityDiagram.png
  docs/images/PersonEditActivityDiagram.png
  docs/images/PersonFindActivityDiagram.png
  docs/images/PersonListActivityDiagram.png
Labels: type.task, priority.high, severity.high

#187 Fix mod overlap tooltip
  src/main/java/syncsquad/teamsync/components/timetable/PersonModulesBlock.java
  src/main/java/syncsquad/teamsync/components/timetable/TimetableChart.java
  src/main/java/syncsquad/teamsync/components/timetable/TooltipBlock.java
Labels: type.enhancement, priority.medium, alpha-bug

#269 Fix PE-D bugs for Developer Guide
  docs/DeveloperGuide.md
Labels: priority.high, severity.high

#272 Fix json module datetime parsing error
  src/main/java/syncsquad/teamsync/storage/JsonAdaptedMeeting.java
  src/main/java/syncsquad/teamsync/storage/JsonAdaptedModule.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/syncsquad/teamsync/storage/JsonAdaptedMeetingTest.java
  src/test/java/syncsquad/teamsync/storage/JsonAdaptedModuleTest.java
  src/test/java/syncsquad/teamsync/storage/JsonAdaptedPersonTest.java
  src/test/java/syncsquad/teamsync/storage/JsonUserPrefsStorageTest.java
  src/test/java/syncsquad/teamsync/storage/StorageManagerTest.java
  src/test/java/syncsquad/teamsync/testutil/TypicalAddressBook.java
Labels: type.bug, priority.low

#206 Fix tooltip bug
  src/main/java/syncsquad/teamsync/components/timetable/TooltipBlock.java
Labels: type.bug, priority.low
