Repository AY2425S2-CS2103T-F10-1/tp, pull requests merged in 2025-03, with the labels that each got.

#44 Add viewmodel tests
  build.gradle
  src/main/java/syncsquad/teamsync/viewmodel/CommandBoxViewModel.java
  src/main/java/syncsquad/teamsync/viewmodel/PersonListViewModel.java
  src/test/java/syncsquad/teamsync/viewmodel/CommandBoxViewModelTest.java
  src/test/java/syncsquad/teamsync/viewmodel/PersonListViewModelTest.java
Labels: type.enhancement, priority.medium

#91 As a group member I can view meetings
  src/main/java/syncsquad/teamsync/logic/commands/ListMeetingsCommand.java
  src/main/java/syncsquad/teamsync/logic/parser/AddressBookParser.java
  src/main/java/syncsquad/teamsync/model/meeting/Meeting.java
  src/test/java/syncsquad/teamsync/logic/commands/ListMeetingsTest.java
Labels: type.story, priority.high, priority.MVP

#93 Add viewmodel tests
  src/test/java/syncsquad/teamsync/viewmodel/MainViewModelTest.java
  src/test/java/syncsquad/teamsync/viewmodel/MeetingListViewModelTest.java
  src/test/java/syncsquad/teamsync/viewmodel/ResultDisplayViewModelTest.java
Labels: priority.medium

#106 Check for conflict when adding modules
  src/main/java/syncsquad/teamsync/logic/Messages.java
  src/main/java/syncsquad/teamsync/logic/commands/AddModuleCommand.java
  src/main/java/syncsquad/teamsync/logic/parser/AddModuleCommandParser.java
  src/main/java/syncsquad/teamsync/model/module/Day.java
  src/main/java/syncsquad/teamsync/model/module/Module.java
Labels: type.bug, priority.high, severity.high

#107 Check for conflict when adding meetings
  src/main/java/syncsquad/teamsync/logic/commands/AddMeetingCommand.java
  src/main/java/syncsquad/teamsync/logic/parser/AddMeetingCommandParser.java
  src/main/java/syncsquad/teamsync/model/meeting/Meeting.java
  src/test/java/syncsquad/teamsync/logic/commands/AddMeetingCommandTest.java
Labels: type.bug, priority.high, severity.high

#127 Add meetings to timetable
  src/main/java/syncsquad/teamsync/components/timetable/MeetingBlock.java
  src/main/java/syncsquad/teamsync/components/timetable/PersonModulesBlock.java
  src/main/java/syncsquad/teamsync/components/timetable/TimetableChart.java
  src/main/java/syncsquad/teamsync/components/timetable/TimetableDisplayable.java
  src/main/java/syncsquad/teamsync/controller/MainWindowController.java
  src/main/java/syncsquad/teamsync/controller/TimetableChart.java
  src/main/java/syncsquad/teamsync/controller/TimetableController.java
  src/main/java/syncsquad/teamsync/logic/parser/DeleteModuleCommandParser.java
  src/main/java/syncsquad/teamsync/model/meeting/Meeting.java
  src/main/java/syncsquad/teamsync/viewmodel/CurrentWeekViewModel.java
  src/main/java/syncsquad/teamsync/viewmodel/MainViewModel.java
  src/main/java/syncsquad/teamsync/viewmodel/MeetingListViewModel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/syncsquad/teamsync/viewmodel/MeetingListViewModelTest.java
Labels: priority.high
